### ISSUE TITLE
config command does not generate .conf files with event server flags

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/tron-cli#44]
Normally, `tron-cli config` command produces the following files  
tron_nodes/fullnode/full.conf
tron_nodes/soliditynode/sol.conf  
tron_nodes/eventnode/event.conf

But when adding event flags such as  `--dbname  --dbusername  --dbpassword   --eventhttpport   --eventrpcport` it rebuilds the eventnode jar files and never generates the config files.

**Comment by wxue** [comment]
the open-sourced version of tron-grid which this tool is using for set up event service is deprecated.

tron-grid just launched a new version, you can check it out to see that can fit your needs: https://developers.tron.network/reference
