### ISSUE TITLE
Cannot connect to http and rpc using tron-cli 

### ISSUE THREAD

**Issue by BhumikaB** [tronprotocol/tron-cli#47]
I am trying to create webservice of tron:
I have sucessfully installed tron
![tron](https://user-images.githubusercontent.com/45986439/54811528-e5817d80-4cae-11e9-91b6-b51007bfa09e.png)

but when i am connecting through curl it gives me error:
`curl  http://127.0.0.1:58500/`
**

> curl: (7) Failed to connect to 127.0.0.1 port 58500: Connection refused

**

**Comment by wxue** [comment]
58500 is for rpc, while you are curl http; 
use 8500 as you can see as the HTTP url in your screenshot
