### ISSUE TITLE
Build grid api jar failing

### ISSUE THREAD

**Issue by dot-punto-dot** [tronprotocol/tron-cli#48]
![image](https://user-images.githubusercontent.com/8480779/55951481-b2714f00-5c9a-11e9-865e-091ffa79426a.png)

full node, solidity, event jars working fine.  For some reason grid api jar won't build.

Error says "No such file or directory: 'mvn' : 'mvn'

Any help appreciated thanks

**Comment by wxue** [comment]
Can take a look at [Installing Apache Maven](https://maven.apache.org/install.html) which is required by the open sourced version grid api.
