### ISSUE TITLE
'tron-cli' 不是内部或外部命令，也不是可运行的程序 或批处理文件

### ISSUE THREAD

**Issue by caojianmin** [tronprotocol/tron-cli#49]
win10系统安装完troncli，执行tron-cli报错：
(venv) C:\Users\Administrator\Desktop\test\venv\Scripts>pip3.exe install troncli
Collecting troncli
  Using cached https://files.pythonhosted.org/packages/84/49/30d38014783be61ba326e0fc5697c8b975034e32bdcfc850d718c1d2c755/troncli-1.0.6-py3-none-any.whl
Collecting colorama (from troncli)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting requests-toolbelt (from troncli)
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting Pygments (from troncli)
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Collecting bleach (from troncli)
  Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
Collecting six (from troncli)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting lxml (from troncli)
  Using cached https://files.pythonhosted.org/packages/bc/87/c3cecadcb5d7924cd71724b177343149cfc3609a89b197a991ac8593ed8c/lxml-4.4.1-cp37-cp37m-win_amd64.whl
Collecting pkginfo (from troncli)
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting requests (from troncli)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting webencodings (from troncli)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting psutil (from troncli)
  Using cached https://files.pythonhosted.org/packages/7c/58/f5d68ddca37480d8557b8566a20bf6108d7e1c6c9b9208ee0786e0cd012b/psutil-5.6.3-cp37-cp37m-win_amd64.whl
Collecting tqdm (from troncli)
  Using cached https://files.pythonhosted.org/packages/02/56/60a5b1c2e634d8e4ff89c7bab47645604e19658f448050a21facffd43796/tqdm-4.33.0-py2.py3-none-any.whl
Collecting docutils (from troncli)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting idna (from troncli)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi (from troncli)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting urllib3 (from troncli)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting chardet (from troncli)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cbox (from troncli)
  Using cached https://files.pythonhosted.org/packages/0d/b6/0f8a37986a0cddff8e33bb871040dbaab1f21797abf8ad85f250c57c4c6c/cbox-0.5.0-py3-none-any.whl
Collecting readme-renderer (from troncli)
  Using cached https://files.pythonhosted.org/packages/c3/7e/d1aae793900f36b097cbfcc5e70eef82b5b56423a6c52a36dce51fedd8f0/readme_renderer-24.0-py2.py3-none-any.whl
Installing collected packages: colorama, certifi, chardet, idna, urllib3, requests, requests-toolbelt, Pygments, six, webencodings, bleach, lxml, pkginfo, psutil, tqdm, docutils, cbox, readme-renderer, troncli
Successfully installed Pygments-2.4.2 bleach-3.1.0 cbox-0.5.0 certifi-2019.6.16 chardet-3.0.4 colorama-0.4.1 docutils-0.15.2 idna-2.8 lxml-4.4.1 pkginfo-1.5.0.1 psutil-5.6.3 readme-renderer-24.0 requests-2.22.0 requests-toolbelt-0.9.1 six-1.12.0 tqdm-4.33.0 troncli-1.0.6 urllib3-1.25.3 webencodings-0.5.1
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(venv) C:\Users\Administrator\Desktop\test\venv\Scripts>tron-cli
'tron-cli' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by wxue** [comment]
1. 这个python版本的只支持mac和linux，windows要改代码才可以跑。
2. 可以试一下go版本的 https://github.com/TRON-US/go-tron-cli 。可以根据你的系统和架构编译成你需要的binary。
3. 这个项目已经迁移到https://github.com/TRON-US/tron-cli 并推荐使用以后会持续更新的https://github.com/TRON-US/go-tron-cli。

__Issue closed due to project moving.__
