### ISSUE TITLE
post 'https://api.trongrid.io/wallet/createaddress' Fail

### ISSUE THREAD

**Issue by zhaosha19850618** [tronprotocol/tron-cli#5]
import requests
url = 'https://api.trongrid.io/wallet/createaddress'
res = requests.post(url,{'value':'iamfromchina'})
>>> res.status_code
200
>>> res.content
**'{"Error":"class org.tron.core.services.http.JsonFormat$ParseException : 1:1: Expected \\"{\\"."}\n'**

**Comment by wxue** [comment]
duplicate to issue [Create Address result difference #6](https://github.com/tronprotocol/tron-cli/issues/6#issue-385554912)
